### ISSUE TITLE
Working docker-compose.yaml

### ISSUE THREAD

**Issue by marcozambi** [projecthorus/radiosonde_auto_rx#566]
First and foremost, thanks for this fantastic work.
I'd like to suggest amending the basic docker-compose.yml offered in the Docker installation guide.
I tried and tested it on my RaspberryPi 3 a few hours ago.
It assumes that the station.cfg file and the log directory are located in the same directory where docker-compose.yml is.

```
version: "3"
services:
  radiosonde_auto_rx:
    container_name: radiosonde_auto_rx
    devices:
      - /dev/bus/usb
    image: ghcr.io/projecthorus/radiosonde_auto_rx:latest
    network_mode: host
    restart: always
    volumes:
      - ./station.cfg:/opt/auto_rx/station.cfg:ro
      - ./log:/opt/auto_rx/log
```
